### PR TITLE
Adding simple express server that redirects to this repo

### PR DESCRIPTION
**Pull request by gruselhaus**

### CODE REVIEW

**Comment by gruselhaus** [comment]
@SolarLiner yeah, but does it work with https?

**Comment by SolarLiner** [comment]
I mean, if all you do is a redirect, there is no point in having HTTPS set up

**Comment by SolarLiner** [comment]
But if you need to, then you can use the same handler function and create both an http and https server.

**Comment by SolarLiner** [comment]
In any case, Heroku takes care of the HTTPS traffic (serving the application's endpoint to both), and also your current setup does *not* enable HTTPS with express.

**Pull request merged**
