### PR TITLE
Migrate to Akairo

### PR DESCRIPTION
**Pull request by GamesProSeif**
This pull request bumps the bot to use [Discord.js Master](https://discord.js.org/#/docs/main/master/general/welcome) and use [Akairo](https://discord-akairo.github.io/#/docs/main/master/general/welcome) which an OOP discord.js framework that eases bot production, and makes it easily scale-able. You might notice in the commands how easy it is to setup one, and especially collecting arguments.

I have tried to maintain the behaviour of the bot as far as I could, and did not mess with the commands and its execution. I have tested all the new changes, and I hopefully did not miss anything.

> Important notice:
By bumping discord.js to master, it allows the usage of the latest features added to the library and benefit the most out of the [Discord API](https://discordapp.com/developers/docs/intro). This also means there are breaking changes to the library, and you'll be required to check the [master documentation](https://discord.js.org/#/docs/main/master/general/welcome) in case of any issues you face. A helpful [guide](https://discordjs.guide/additional-info/changes-in-v12.html) can assist you which shows changes from stable to master.

I've decided not to continue any further with integrating a database because I'm waiting for this to be reviewed and merged first. Please inform me if you are not satisfied with specific changes.

Waiting for your review.

### CODE REVIEW

**Comment by nobobo1234** [comment]
Hmmm even though I like the OOP style I don't like the framework itself. I'm someone who likes to keep things low-level and removing the whole command handler seems too much to me. I do however like the OOP commands so maybe you could do something with that?

**Comment by GamesProSeif** [comment]
Akairo has its own command handler which has  significantly huge features. It still does the same thing really as the old one, but with the ability to use much greater utility functions. I can't the command handler if I'm using Akairo, but I can extend its class to have the same methods you had in the old one. For example, I've seen you made a check for each command and made sure it has an `info` property (which was renamed to `description` by the way), so I extended Akairo's `CommandHandler` to do that check once a command loads ([extended CommandHandler](https://github.com/GamesProSeif/trainbot/blob/patch-1/src/structures/TrainCommandHandler.js#L10)).

If you'd like, I can do that change, but believe me, Akairo is worth it - it saves tons of lines of code. You can check a [full project](https://github.com/GamesProSeif/jr-gopnik) I made which uses the most out of Akairo and judge yourself.

**Comment by GamesProSeif** [comment]
This pull request should be complete by now. I have added latest changes you made, database support, initial settings model and a dynamic prefix function. If you wish for a talk regarding the command handler, we can talk on Discord.

**Comment by nobobo1234** [comment]
Sorry for the late response, but I feel like it all looks overcomplicated. You have all this unnecessary stuff added to your command files which I frankly don't quite like. We _could_ however add this to a seperate branch or repo to show the differences between using a framework and just pure Discord.JS. If we do want to make it easier we can always build our own framework kinda thing, which I like more, because then I have full control.

**Pull request closed without merging**
